# Generated by Django 5.2.8 on 2026-07-05 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField()),
                (
                    "completion_trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("highlight_text", models.TextField()),
                (
                    "avg_completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_xp_earned", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_weeklyinsight",
                "ordering": ["-week_start"],
            },
        ),
    ]
