# Generated by Django 5.2.8 on 2026-07-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyinsight",
            name="best_routine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="routines.routine",
            ),
        ),
    ]
