# Generated by Django 5.2.8 on 2026-07-05 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeScoreSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("fitness_score", models.PositiveIntegerField(default=75)),
                ("learning_score", models.PositiveIntegerField(default=75)),
                ("work_score", models.PositiveIntegerField(default=75)),
                ("mental_health_score", models.PositiveIntegerField(default=75)),
                ("health_score", models.PositiveIntegerField(default=75)),
                ("sleep_score", models.PositiveIntegerField(default=75)),
                ("finance_score", models.PositiveIntegerField(default=75)),
                ("personal_score", models.PositiveIntegerField(default=75)),
                ("discipline_score", models.PositiveIntegerField(default=75)),
                ("overall_score", models.PositiveIntegerField(default=75)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Lost", "Lost"),
                            ("Improving", "Improving"),
                            ("Consistent", "Consistent"),
                            ("Excellent", "Excellent"),
                            ("Elite", "Elite"),
                            ("Legend", "Legend"),
                        ],
                        default="Consistent",
                        max_length=30,
                    ),
                ),
                (
                    "ai_analysis",
                    models.TextField(
                        blank=True,
                        default="Your life systems are running with solid equilibrium.",
                    ),
                ),
                ("improvement_suggestions", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_lifescoresnapshot",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
