# Generated by Django 5.2.8 on 2026-07-05 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_lifescoresnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOSGoals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("water_goal_ml", models.PositiveIntegerField(default=3000)),
                ("workout_goal_exercises", models.PositiveIntegerField(default=8)),
                ("study_goal_mins", models.PositiveIntegerField(default=120)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="os_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User OS Goals",
                "verbose_name_plural": "User OS Goals",
                "db_table": "analytics_userosgoals",
            },
        ),
        migrations.CreateModel(
            name="DailyOSMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("water_ml", models.PositiveIntegerField(default=0)),
                ("workout_exercises", models.PositiveIntegerField(default=0)),
                ("study_mins", models.PositiveIntegerField(default=0)),
                ("pomodoro_sessions", models.PositiveIntegerField(default=0)),
                ("focus_mins", models.PositiveIntegerField(default=0)),
                ("daily_xp", models.PositiveIntegerField(default=0)),
                (
                    "daily_completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_os_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_dailyosmetrics",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
