# Generated by Django 5.2.8 on 2026-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_userosgoals_dailyosmetrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifescoresnapshot",
            name="title",
            field=models.CharField(
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Average", "Average"),
                    ("Poor", "Poor"),
                    ("Critical", "Critical"),
                    ("Initializing", "Initializing"),
                    ("Lost", "Lost"),
                    ("Improving", "Improving"),
                    ("Consistent", "Consistent"),
                    ("Elite", "Elite"),
                    ("Legend", "Legend"),
                ],
                default="Good",
                max_length=30,
            ),
        ),
    ]
