# Generated by Django 5.2.8 on 2026-07-11 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_fix_lifescoresnapshot_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("goal", models.PositiveIntegerField()),
                ("unit", models.CharField(max_length=50)),
                ("icon", models.CharField(default="check", max_length=50)),
                ("color", models.CharField(default="blue", max_length=50)),
                ("step_size", models.PositiveIntegerField(default=1)),
                ("reset_daily", models.BooleanField(default=True)),
                ("show_in_reports", models.BooleanField(default=True)),
                ("show_on_dashboard", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_customwidget",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WidgetLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="analytics.customwidget",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_widgetlog",
                "ordering": ["-date"],
                "unique_together": {("widget", "date")},
            },
        ),
    ]
