# Generated by Django 5.2.8 on 2026-07-11 06:22

from django.db import migrations


def migrate_os_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserOSGoals = apps.get_model("analytics", "UserOSGoals")
    DailyOSMetrics = apps.get_model("analytics", "DailyOSMetrics")
    CustomWidget = apps.get_model("analytics", "CustomWidget")
    WidgetLog = apps.get_model("analytics", "WidgetLog")

    for user in User.objects.all():
        # Get or default goals
        goals = UserOSGoals.objects.filter(user=user).first()
        water_goal = goals.water_goal_ml if goals else 3000
        workout_goal = goals.workout_goal_exercises if goals else 8
        study_goal = goals.study_goal_mins if goals else 120

        # Create Custom Widgets
        water_widget = CustomWidget.objects.create(
            user=user, name="Water Intake", goal=water_goal, unit="ml",
            icon="droplets", color="cyan-400", step_size=250, display_order=1
        )
        workout_widget = CustomWidget.objects.create(
            user=user, name="Workout", goal=workout_goal, unit="exercises",
            icon="dumbbell", color="rose-400", step_size=1, display_order=2
        )
        study_widget = CustomWidget.objects.create(
            user=user, name="Deep Study", goal=study_goal, unit="minutes",
            icon="book-open", color="purple-400", step_size=15, display_order=3
        )
        focus_widget = CustomWidget.objects.create(
            user=user, name="Focus Tracker", goal=120, unit="minutes",
            icon="clock", color="emerald-400", step_size=25, display_order=4
        )

        # Migrate Daily Metrics
        metrics = DailyOSMetrics.objects.filter(user=user)
        logs_to_create = []
        for m in metrics:
            if m.water_ml > 0:
                logs_to_create.append(WidgetLog(widget=water_widget, date=m.date, progress=m.water_ml))
            if m.workout_exercises > 0:
                logs_to_create.append(WidgetLog(widget=workout_widget, date=m.date, progress=m.workout_exercises))
            if m.study_mins > 0:
                logs_to_create.append(WidgetLog(widget=study_widget, date=m.date, progress=m.study_mins))
            if m.focus_mins > 0:
                logs_to_create.append(WidgetLog(widget=focus_widget, date=m.date, progress=m.focus_mins))
        
        if logs_to_create:
            WidgetLog.objects.bulk_create(logs_to_create)


def reverse_migration(apps, schema_editor):
    CustomWidget = apps.get_model("analytics", "CustomWidget")
    CustomWidget.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_add_custom_widgets"),
    ]

    operations = [
        migrations.RunPython(migrate_os_data, reverse_migration),
    ]

