# Generated by Django 5.2.8 on 2026-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_migrate_custom_widgets"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetlog",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
