# Generated by Django 5.2.8 on 2026-07-05 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("streak", "Streak"),
                            ("badge", "Badge"),
                            ("milestone", "Milestone"),
                            ("reminder", "Reminder"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("action_url", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
