# Generated by Django 5.2.8 on 2026-07-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emailreminderschedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
