# Generated by Django 5.2.8 on 2026-07-24 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_delete_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("template_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("skipped", "Skipped"),
                            ("bounced", "Bounced"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("send_time", models.DateTimeField(blank=True, null=True)),
                ("delivery_time", models.DateTimeField(blank=True, null=True)),
                ("open_time", models.DateTimeField(blank=True, null=True)),
                ("click_time", models.DateTimeField(blank=True, null=True)),
                ("bounce_time", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("failure_reason", models.TextField(blank=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_emaillog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailIdempotency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="processing", max_length=50)),
                (
                    "email_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.emaillog",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_emailidempotency",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("morning_mail_enabled", models.BooleanField(default=True)),
                ("night_mail_enabled", models.BooleanField(default=True)),
                ("weekly_report_enabled", models.BooleanField(default=True)),
                ("monthly_report_enabled", models.BooleanField(default=True)),
                ("marketing_mail_enabled", models.BooleanField(default=True)),
                ("recovery_mail_enabled", models.BooleanField(default=True)),
                ("trial_mail_enabled", models.BooleanField(default=True)),
                ("push_notifications_enabled", models.BooleanField(default=False)),
                ("push_subscription_info", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notificationpreference",
            },
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(fields=["status"], name="notificatio_status_18a272_idx"),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["template_name"], name="notificatio_templat_a00c20_idx"
            ),
        ),
    ]
