# Generated by Django 5.2.8 on 2026-07-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0005_emaillog_emailidempotency_notificationpreference_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmailIdempotency",
        ),
        migrations.DeleteModel(
            name="EmailLog",
        ),
    ]
