# Generated by Django 5.2.8 on 2026-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time_preference",
            field=models.CharField(
                choices=[
                    ("morning", "Morning Person"),
                    ("afternoon", "Afternoon Person"),
                    ("evening", "Evening Person"),
                    ("night", "Night Owl"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
    ]
