# Generated by Django 5.2.8 on 2026-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_time_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("trial", "14-Day Free Trial"),
                    ("monthly", "Monthly Plan (₹99)"),
                    ("6_month", "6-Month Plan (₹399)"),
                    ("12_month", "12-Month Plan (₹699)"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="razorpay_customer_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="razorpay_subscription_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="renewal_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial Active"),
                    ("active", "Subscription Active"),
                    ("expired", "Trial/Plan Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
