# Generated by Django 5.2.8 on 2026-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_auto_renew_user_invoice_number_user_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_method",
            field=models.CharField(blank=True, default="razorpay", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="plan_name",
            field=models.CharField(
                blank=True, default="7-Day Free Trial", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_used",
            field=models.BooleanField(default=False),
        ),
    ]
