# Generated by Django 5.2.8 on 2026-07-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_extend_trial_to_8_days"),
        ("users", "0004_user_amount_paid_user_currency_user_invoice_id_and_more"),
    ]

    operations = []
