# Generated by Django 5.2.8 on 2026-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_20260710_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("trial", "8-Day Free Trial"),
                    ("monthly", "Monthly Plan (₹99)"),
                    ("6_month", "6-Month Plan (₹399)"),
                    ("12_month", "12-Month Plan (₹699)"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
