# Generated by Django 5.2.8 on 2026-07-13 06:43

from django.db import migrations
from datetime import timedelta

def migrate_trials(apps, schema_editor):
    User = apps.get_model('users', 'User')
    trial_users = User.objects.filter(
        subscription_status='trial', 
        trial_start__isnull=False, 
        trial_end__isnull=False
    )
    for user in trial_users:
        diff = user.trial_end - user.trial_start
        # If their trial length is roughly 7-8 days (allow slight buffer)
        if timedelta(days=6) <= diff <= timedelta(days=9):
            user.trial_end = user.trial_start + timedelta(days=14)
            user.save(update_fields=['trial_end'])

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_plan_type"),
    ]

    operations = [
        migrations.RunPython(migrate_trials, reverse_code=migrations.RunPython.noop),
    ]
