# Generated by Django 5.2.8 on 2026-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_migrate_trial_to_14_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("trial", "14-Day Free Trial"),
                    ("monthly", "Monthly Plan (₹99)"),
                    ("6_month", "6-Month Plan (₹399)"),
                    ("12_month", "12-Month Plan (₹699)"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
