# Generated by Django 5.2.8 on 2026-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_plan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plan_name",
            field=models.CharField(blank=True, default="Free Plan", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("free", "Free Plan"),
                    ("trial", "14-Day Free Trial"),
                    ("monthly", "Monthly Plan (₹99)"),
                    ("6_month", "6-Month Plan (₹399)"),
                    ("12_month", "12-Month Plan (₹699)"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("trial", "Trial Active"),
                    ("active", "Subscription Active"),
                    ("expired", "Trial/Plan Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
