# Generated by Django 5.2.8 on 2026-08-10 11:48

from django.db import migrations


def migrate_trials(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(subscription_status='trial').update(
        subscription_status='free',
        plan_type='free',
        trial_start=None,
        trial_end=None,
        trial_used=False
    )

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_plan_name_alter_user_plan_type_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_trials),
    ]
