# Generated by Django 5.0.6 on 2026-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_migrate_trials_to_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_seed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_on_leaderboard",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("free", "Free Plan"),
                    ("trial", "Legacy Trial"),
                    ("monthly", "Monthly Plan (₹49)"),
                    ("6_month", "6-Month Plan (₹265)"),
                    ("12_month", "12-Month Plan (₹499)"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
