# Generated by Django 5.2.8 on 2026-07-05 09:24

import apps.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="color",
            field=models.CharField(
                default="#6C5EF8",
                max_length=7,
                validators=[apps.core.validators.validate_hex_color],
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="routine",
            name="icon",
            field=models.CharField(
                default="⚡",
                max_length=10,
                validators=[apps.core.validators.validate_emoji],
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="name",
            field=models.CharField(
                max_length=100, validators=[apps.core.validators.validate_routine_name]
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, validators=[apps.core.validators.validate_sort_order]
            ),
        ),
        migrations.AlterField(
            model_name="routineschedule",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.core.validators.validate_days_of_week],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[apps.core.validators.validate_duration_minutes],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=200, validators=[apps.core.validators.validate_task_name]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, validators=[apps.core.validators.validate_sort_order]
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["user", "is_active"], name="routines_ro_user_id_4eb614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routine",
            index=models.Index(
                fields=["user", "time_of_day"], name="routines_ro_user_id_0baa87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["routine", "is_active"], name="routines_ta_routine_3c1fc6_idx"
            ),
        ),
    ]
