# Generated by Django 5.2.8 on 2026-07-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0003_alter_routine_color_alter_routine_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
