# Generated by Django 5.2.8 on 2026-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("retrying", "Retrying"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                    ("opened", "Opened"),
                    ("clicked", "Clicked"),
                    ("bounced", "Bounced"),
                    ("complained", "Complained"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
    ]
