# Generated by Django 5.2.8 on 2026-08-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_alter_emaillog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="html_content",
            field=models.TextField(
                blank=True, help_text="The exact HTML payload sent."
            ),
        ),
    ]
