# Generated by Django 5.2.8 on 2026-08-08 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_emaillog_html_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplateConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., missed_3_days)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "html_file_path",
                    models.CharField(
                        help_text="Path to HTML template, e.g., emails/retention/missed_3_days.html",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "variables_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required context variables",
                    ),
                ),
            ],
            options={
                "db_table": "emails_emailtemplateconfig",
            },
        ),
        migrations.AddField(
            model_name="emaillog",
            name="segment",
            field=models.CharField(
                blank=True,
                help_text="User segment targeted (e.g., missed_3_days)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("retrying", "Retrying"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                    ("opened", "Opened"),
                    ("clicked", "Clicked"),
                    ("bounced", "Bounced"),
                    ("spam", "Spam"),
                    ("complained", "Complained"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubjectLineVariation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_text", models.CharField(max_length=255)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_variations",
                        to="emails.emailtemplateconfig",
                    ),
                ),
            ],
            options={
                "db_table": "emails_subjectlinevariation",
                "ordering": ["-open_count"],
            },
        ),
        migrations.AddField(
            model_name="emaillog",
            name="subject_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.subjectlinevariation",
            ),
        ),
    ]
