# Generated by Django 5.2.8 on 2026-08-08 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_emailtemplateconfig_emaillog_segment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBounceSuppress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hard_bounce", "Hard Bounce"),
                            ("soft_bounce", "Soft Bounce"),
                            ("spam_complaint", "Spam Complaint"),
                            ("unsubscribed", "Unsubscribed"),
                            ("manual", "Manually Suppressed"),
                            ("blocked", "Blocked by Provider"),
                        ],
                        default="hard_bounce",
                        max_length=20,
                    ),
                ),
                (
                    "provider_event",
                    models.CharField(
                        blank=True, help_text="Raw Brevo event name", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Suppressed Email",
                "verbose_name_plural": "Suppressed Emails",
                "db_table": "emails_emailbouncesuppress",
                "ordering": ["-created_at"],
            },
        ),
    ]
