# Generated by Django 5.2.8 on 2026-07-05 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HardcoreAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="Trophy", max_length=50)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Hidden", "Hidden"),
                            ("Secret", "Secret"),
                            ("Legendary", "Legendary"),
                            ("Mythic", "Mythic"),
                            ("Impossible", "Impossible"),
                        ],
                        default="Secret",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(default="general", max_length=50)),
                ("target_value", models.PositiveIntegerField(default=100)),
                ("xp_reward", models.PositiveIntegerField(default=500)),
                ("coin_reward", models.PositiveIntegerField(default=100)),
            ],
            options={
                "db_table": "rewards_hardcoreachievement",
            },
        ),
        migrations.CreateModel(
            name="StreakFreeze",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total_used", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_freeze",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rewards_streakfreeze",
            },
        ),
        migrations.CreateModel(
            name="ForgeCoinTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("task_complete", "Task Completed"),
                            ("perfect_day", "Perfect Day Bonus"),
                            ("streak_bonus", "Streak Bonus"),
                            ("achievement", "Achievement Unlocked"),
                            ("store_purchase", "Store Purchase"),
                            ("streak_freeze_use", "Streak Freeze Consumed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rewards_forgecointransaction",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rewards_for_user_id_da7eaf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeagueRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("Bronze", "Bronze"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Platinum", "Platinum"),
                            ("Diamond", "Diamond"),
                            ("Master", "Master"),
                            ("Grandmaster", "Grandmaster"),
                            ("Legend", "Legend"),
                            ("Mythic", "Mythic"),
                            ("Immortal", "Immortal"),
                        ],
                        default="Bronze",
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=100)),
                ("rank", models.PositiveIntegerField(default=9999)),
                ("country", models.CharField(default="United States", max_length=50)),
                ("city", models.CharField(default="San Francisco", max_length=50)),
                (
                    "university",
                    models.CharField(default="DeepMind University", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rewards_leagueranking",
                "indexes": [
                    models.Index(
                        fields=["division", "-score"],
                        name="rewards_lea_divisio_78c426_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserHardcoreAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("seen", models.BooleanField(default=False)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards.hardcoreachievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardcore_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rewards_userhardcoreachievement",
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
