# Generated by Django 5.2.8 on 2026-07-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0003_hardcoreachievement_streakfreeze_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardcoreachievement",
            name="coin_reward",
        ),
        migrations.DeleteModel(
            name="ForgeCoinTransaction",
        ),
    ]
