# Generated by Django 5.2.8 on 2026-07-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_remove_hardcoreachievement_coin_reward_and_more"),
        ("routines", "0004_routine_deleted_at_routine_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="xptransaction",
            name="reverted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="xptransaction",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="xp_transactions",
                to="routines.task",
            ),
        ),
    ]
