# Generated by Django 5.0.6 on 2026-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0005_xptransaction_reverted_xptransaction_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_position", models.PositiveSmallIntegerField(unique=True)),
                ("title_name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "db_table": "rewards_leaderboardtitle",
                "ordering": ["rank_position"],
            },
        ),
    ]
