# Generated by Django 5.2.8 on 2026-07-05 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("local_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                ("mood", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_actual", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "completions_completion",
            },
        ),
        migrations.CreateModel(
            name="DayLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField()),
                ("tasks_scheduled", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("routines_completed", models.PositiveIntegerField(default=0)),
                ("is_streak_day", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "completions_daylog",
            },
        ),
    ]
