# Generated by Django 5.2.8 on 2026-07-05 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("completions", "0001_initial"),
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="completion",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="routines.task",
            ),
        ),
    ]
