# Generated by Django 5.2.8 on 2026-07-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("completions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="completion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="daylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="completion",
            index=models.Index(
                fields=["user", "local_date"], name="completions_user_id_c37ff4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="completion",
            unique_together={("task", "user", "local_date")},
        ),
        migrations.AddIndex(
            model_name="daylog",
            index=models.Index(
                fields=["user", "-log_date"], name="completions_user_id_74e1ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="daylog",
            unique_together={("user", "log_date")},
        ),
    ]
