# Generated by Django 5.2.8 on 2026-07-05 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreakRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("grace_period_used", models.BooleanField(default=False)),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_records",
                        to="routines.routine",
                    ),
                ),
            ],
            options={
                "db_table": "streaks_streakrecord",
            },
        ),
    ]
