# Generated by Django 5.2.8 on 2026-07-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("streaks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="streakrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streaks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="streakrecord",
            index=models.Index(
                fields=["user", "routine"], name="streaks_str_user_id_88eb4a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streakrecord",
            unique_together={("user", "routine")},
        ),
    ]
