import pytest
from io import StringIO
from django.core.management import call_command
from django.contrib.auth import get_user_model
from django.test import TestCase
from apps.emails.models import EmailBounceSuppress, EmailIdempotency, EmailLog
from unittest.mock import patch

User = get_user_model()

class PriceDropCampaignTests(TestCase):
    def setUp(self):
        self.user1 = User.objects.create(username="user1", email="user1@example.com", is_active=True)
        self.user2 = User.objects.create(username="user2", email="user2@example.com", is_active=True)
        self.user_empty = User.objects.create(username="empty", email="", is_active=True)
        self.user_inactive = User.objects.create(username="inactive", email="inactive@example.com", is_active=False)
        self.user_suppressed = User.objects.create(username="suppressed", email="suppressed@example.com", is_active=True)
        
        EmailBounceSuppress.objects.create(email=self.user_suppressed.email)
        
        # Clear logs generated by post_save signals (welcome emails)
        EmailLog.objects.all().delete()

    @patch("apps.emails.tasks.send_email_task.delay")
    def test_campaign_eligibility_and_queue(self, mock_task):
        out = StringIO()
        call_command("send_price_drop_campaign", stdout=out)
        
        output = out.getvalue()
        self.assertIn("Final Eligible Recipients: 2", output)  # user1 and user2
        self.assertEqual(EmailLog.objects.filter(segment="price_drop").count(), 2)
        
        # Check that empty email, inactive, and suppressed are ignored
        queued_emails = list(EmailLog.objects.values_list("recipient", flat=True))
        self.assertIn("user1@example.com", queued_emails)
        self.assertIn("user2@example.com", queued_emails)
        self.assertNotIn("suppressed@example.com", queued_emails)
        self.assertNotIn("", queued_emails)

    @patch("apps.emails.tasks.send_email_task.delay")
    def test_idempotency_prevents_duplicates(self, mock_task):
        # Run first time
        call_command("send_price_drop_campaign")
        self.assertEqual(EmailLog.objects.filter(segment="price_drop").count(), 2)
        
        # Run second time
        out = StringIO()
        call_command("send_price_drop_campaign", stdout=out)
        
        output = out.getvalue()
        self.assertIn("Users Already Sent (Campaign price_drop_v1): 2", output)
        self.assertIn("Final Eligible Recipients: 0", output)
        
        # Count should still be 2
        self.assertEqual(EmailLog.objects.filter(segment="price_drop").count(), 2)

    @patch("apps.emails.tasks.send_email_task.delay")
    def test_dry_run(self, mock_task):
        out = StringIO()
        call_command("send_price_drop_campaign", dry_run=True, stdout=out)
        
        output = out.getvalue()
        self.assertIn("DRY RUN MODE ACTIVE", output)
        self.assertIn("Final Eligible Recipients: 2", output)
        
        # No emails should be queued
        self.assertEqual(EmailLog.objects.filter(segment="price_drop").count(), 0)

    @patch("apps.emails.tasks.send_email_task.delay")
    def test_campaign_id_isolation(self, mock_task):
        call_command("send_price_drop_campaign", campaign_id="v1")
        self.assertEqual(EmailLog.objects.filter(segment="price_drop").count(), 2)
        
        # Different campaign ID should send again
        call_command("send_price_drop_campaign", campaign_id="v2")
        self.assertEqual(EmailLog.objects.filter(segment="price_drop").count(), 4)

    def test_template_rendering(self):
        from apps.emails.core.builder import EmailBuilder
        content = EmailBuilder.build_content("price_drop", {
            "user_name": "Test", 
            "app_url": "http://localhost",
        })
        
        self.assertIn("Your discipline just got cheaper.", content["html"])
        self.assertIn("₹49/month", content["html"])
        self.assertIn("₹49/month", content["text"])
        self.assertIn("http://localhost/pricing", content["html"])
